/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc.account;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

/**
 *
 * @author Mike Chang
 */
public class LoginPage extends JFrame {
     private String user;
     private char[] password;
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginpanel = new javax.swing.JPanel();
        loginlabel = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        psswlabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        usernametext = new javax.swing.JTextField();
        usernameWarn = new javax.swing.JLabel();
        psswWarn = new javax.swing.JLabel();
        psswtext = new javax.swing.JPasswordField();
        fullwarning = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 204));
        setFont(new java.awt.Font("Bookman Old Style", 3, 10)); // NOI18N

        loginpanel.setBackground(new java.awt.Color(51, 51, 51));
        loginpanel.setName("loginpanel"); // NOI18N

        loginlabel.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        loginlabel.setForeground(new java.awt.Color(255, 255, 255));
        loginlabel.setText("Login");

        usernamelabel.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        usernamelabel.setForeground(new java.awt.Color(255, 255, 255));
        usernamelabel.setText("Username :");

        psswlabel.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        psswlabel.setForeground(new java.awt.Color(255, 255, 255));
        psswlabel.setText("Password :");

        loginBtn.setBackground(new java.awt.Color(204, 255, 204));
        loginBtn.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(51, 51, 51));
        loginBtn.setText("Login");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        usernametext.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        usernametext.setForeground(new java.awt.Color(51, 51, 51));

        usernameWarn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameWarn.setForeground(new java.awt.Color(255, 51, 51));

        psswWarn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        psswWarn.setForeground(new java.awt.Color(255, 51, 51));

        fullwarning.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fullwarning.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout loginpanelLayout = new javax.swing.GroupLayout(loginpanel);
        loginpanel.setLayout(loginpanelLayout);
        loginpanelLayout.setHorizontalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addComponent(psswlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(psswWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psswtext, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(133, 133, 133))
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addComponent(usernamelabel)
                        .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginpanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(loginpanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(129, 129, 129))))
            .addGroup(loginpanelLayout.createSequentialGroup()
                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(loginBtn))
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(fullwarning)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        loginpanelLayout.setVerticalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(loginlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamelabel)
                    .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameWarn)
                .addGap(50, 50, 50)
                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psswlabel)
                    .addComponent(psswtext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(psswWarn)
                .addGap(61, 61, 61)
                .addComponent(loginBtn)
                .addGap(28, 28, 28)
                .addComponent(fullwarning)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        usernamelabel.getAccessibleContext().setAccessibleName("usernamelabel");
        loginBtn.getAccessibleContext().setAccessibleName("LoginBtn");
        usernametext.getAccessibleContext().setAccessibleName("UsernameText");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        loginBtn.setForeground(Color.orange);
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        user =usernametext.getText();
        password = psswtext.getPassword();
       if((user.length()>3 && user.length()<21)&& (password.length>7&& password.length<51)){
            try { 
                
               
                Controller control= new Controller();
                control.loginCheck(user, password);
                 boolean v=Controller.visible;
                setVisible(v);
               
            } catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        
         
         
               }
               else if((user.length()<4 || user.length()>21)&& (password.length>7&& password.length<51)){
                   usernameWarn.setText("4-20 characters needed!");
                   
               }
               else if((user.length()<4 || user.length()>21)&& (password.length<8|| password.length>50)){
                   usernameWarn.setText("4-20 characters needed!");
                     psswWarn.setText("8-50 characters needed!");
               }
               
               else{
                   psswWarn.setText("8-50 characters needed!");
               }
     
    }//GEN-LAST:event_loginBtnActionPerformed
 
    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        loginBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_loginBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 try {
            	   for(LookAndFeelInfo info: UIManager.getInstalledLookAndFeels()) {
            		   if("Windows".equals(info.getName())) {
            			   UIManager.setLookAndFeel(info.getClassName());
            			   break;
            		   }
            	   }
            	   
               }catch(Exception e) {
        		   
        	   }
               
              new LoginPage().setVisible(true);
				
			}
                
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JLabel fullwarning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginlabel;
    public static javax.swing.JPanel loginpanel;
    private javax.swing.JLabel psswWarn;
    private javax.swing.JLabel psswlabel;
    private javax.swing.JPasswordField psswtext;
    private javax.swing.JLabel usernameWarn;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JTextField usernametext;
    // End of variables declaration//GEN-END:variables
}
